spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: he182335nhudinhcan@gmail.com
    password: mnxhcfblsmahkcse
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  thymeleaf:
#    prefix: classpath:/templates/frontend/
#    suffix: .html
#    encoding: UTF-8
#    mode: HTML
#    cache: false
#    servlet:
#      content-type: text/html

jwt:
  secret: "843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3"

google:
  oauth:
    client-id: "91404244696-0v0e8sdibqqr478nuckhd1hr7kq8anim.apps.googleusercontent.com"
